### ISSUE TITLE
Is this project still available?

### ISSUE THREAD

**Issue by maryjeck** [thatmarcel/beepserv-rewrite#10]
I am a new user and just jailbroken my iPhone x. Can correctly obtain the registration code 。 But when using beepeer, it always stops connecting.
![c613b0d81e6e3b5dfa4fcd7020b2917](https://github.com/thatmarcel/beepserv-rewrite/assets/4252556/1040f14d-6f9c-4b66-8054-07d8ee78f204)

The last log message is ： Sending dictionary string

Did I do any wrong step?

**Comment by thatmarcel** [comment]
Strange! Do you get an error message in Beeper Mini after some time?

**Comment by thatmarcel** [comment]
I'll close this issue for now. If it is still relevant, feel free to re-open :)
