### ISSUE TITLE
Use proper PAC functions rather than relying on MSHookFunction

### ISSUE THREAD

**Issue by JJTech0130** [thatmarcel/beepserv-rewrite#11]
In https://github.com/thatmarcel/beepserv-rewrite/blob/main/IdentityServices/bp_ids_hooking_utils.x you wrote:
```objc
// Just calling nac_sign did not work reliably, so we hook
// it and call the original function we get from MSHookFunction
```

The reason this does not work on arm64e devices is because the pointer you found is not signed with PAC. 
Instead of relying on `MSHookFunction`, you can use the PAC intrinsics directly to sign the pointer:
```objc
#include <ptrauth.h>
ptr = ptrauth_sign_unauthenticated(ptrauth_strip(ptr, ptrauth_key_function_pointer), ptrauth_key_function_pointer, 0);
```

This is described in more detail in [summertriangle's excellent gist on the subject](https://gist.github.com/summertriangle-dev/6b0449ce561f756ac82a4bc3de7af30a)

**Comment by thatmarcel** [comment]
Thanks for the explanation and link to the gist.

I'm not very familiar with the details of how PAC works but that completely explains why directly calling it didn't work. Using the `ptrauth` functions to sign the pointer is definitely much better than using `MSHookFunction` as a workaround.

**Comment by thatmarcel** [comment]
Sorry for the delay. Commit [7fe5d03](https://github.com/thatmarcel/beepserv-rewrite/commit/7fe5d03fc6a0f3f72aec7755c13705f581198bde) replaces the nac_sign hook with proper PAC functions.
