### ISSUE TITLE
Connectivity requirements

### ISSUE THREAD

**Issue by TrustedDeveloper** [thatmarcel/beepserv-rewrite#17]
Does this app require the host iPhone to remain on and connected to WiFi?

**Comment by thatmarcel** [comment]
The iPhone needs to be connected to the internet when Beeper Mini has to re-register with Apple's servers. The intervals where it needs to do this vary. Sometimes you may be fine for hours or days without the iPhone online, but usually re-registration will happen quite frequently.

So, TLDR: Yes, the iPhone should stay on and connected to the internet.
