### ISSUE TITLE
fe9ddfe error when requesting validation data on Iphone 6S

### ISSUE THREAD

**Issue by Heulyn** [thatmarcel/beepserv-rewrite#8]
Hey All, Updated my Iphone 6S from [e0477ea](https://github.com/thatmarcel/beepserv-rewrite/releases/tag/e0477ea) to fe9ddfe and had the exact error that marcel mentioned was possible. Went back to e0477ea and its working perfectly again. Probably just going to stay on that version for now, it seems like a perfect release.

**Comment by thatmarcel** [comment]
Thanks for the report.

Can you try whether release [a686640](https://github.com/thatmarcel/beepserv-rewrite/releases/tag/a686640) fixes the problem on your device?

**Comment by Heulyn** [comment]
> Thanks for the report.
> 
> Can you try whether release [a686640](https://github.com/thatmarcel/beepserv-rewrite/releases/tag/a686640) fixes the problem on your device?

Hey Marcel, I can confirm that a686640 is working as of now, I just installed it obviously, but promising start!

Thanks for your hard work on this project.
Heulyn

**Comment by thatmarcel** [comment]
Great to hear!

I'll close this issue for now, feel free to re-open it if the problem appears again.
